version: '3.8'

services:
  finman-api-gateway:
    image: finman-api-gateway:latest  # Specify the image name and tag
    container_name: finman-gateway-container
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      JWT_SECRET: eDM!":jmx2/QoHBlY'.O8e4?Uy,",9
      JWT_EXPIRE_MINUTE: 20
      FINMAN_USER_URL: finman-user-service:8081
      FINMAN_TRANSACTION_URL: finman-transaction-service:8082
      FINMAN_AUTH_URL: finman-auth-service:8080
      PORT: 8085
      IP: 0.0.0.0
    ports:
      - "8085:8085"
    networks:
      - finman-network
    restart: always

networks:
  finman-network:
    driver: bridge
    external: true

volumes:
  postgres-user-data:
 
